In [1]:
import numpy as np
import sympy


arr1 = np.random.randint(0, 5, size=(3, 4))
print(arr1)
np.linalg.solve(arr1)

[[3 3 3 1]
 [4 0 1 4]
 [4 4 0 0]]


TypeError: _solve_dispatcher() missing 1 required positional argument: 'b'

In [3]:
M = sympy.Matrix(
    [[1, -2, 3, 5, 14], [-2, 4, -5, -10, -26], [2, -4, 6, 11, 29], [-1, 2, -2, -5, -12]]
)

print(M.rref())


(Matrix([
[1, -2, 0, 0, 3],
[0,  0, 1, 0, 2],
[0,  0, 0, 1, 1],
[0,  0, 0, 0, 0]]), (0, 2, 3))


In [5]:
M1 = sympy.Matrix([[1, -1, 2, 4], [2, 1, -1, 1], [3, 3, -4, -2]])
print(M1)
print(M1.rref())

Matrix([[1, -1, 2, 4], [2, 1, -1, 1], [3, 3, -4, -2]])
(Matrix([
[1, 0,  1/3,  5/3],
[0, 1, -5/3, -7/3],
[0, 0,    0,    0]]), (0, 1))
